[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

fuzz_runs = 256
gas_reports = ["*"]
solc_version = '0.8.10'
ffi = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
